=== akassharjun/wdd-tutorials/Tutorial 6/menu.dtd
<!DOCTYPE menu
[
<!ELEMENT menu (heading, sections+)>
<!ELEMENT heading (title, address)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT sections (subtitle, options*)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT options (item, price)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]>

=== akassharjun/wdd-tutorials/Tutorial 6/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE menu
[
<!ELEMENT menu (heading, sections+)>
<!ELEMENT heading (title, address)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT sections (subtitle, options*)>
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT options (item, price)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT price (#PCDATA)>
]> -->

<!DOCTYPE menu SYSTEM "menu.dtd">

<menu>
    <heading>
        <title>Title</title>
        <address>Address</address>
    </heading>
    <sections>
        <subtitle>Subtitle</subtitle>
        <options>
            <item>Item</item>
            <price>Price</price>
        </options>
    </sections>
</menu>
